name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
      
    #- name: Install azure-cli
      #uses: pietrobolcato/install-azure-cli-action@v1.0.1

    #- name: Azure Login with User Credentials
      #run: |
        #az login --use-device-code  # This allows interactive login via a device code
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: /home/runner/work/eShopOnWeb/eShopOnWeb/tests/PublicApiIntegrationTests/bin/Release/net8.0/**        

    #- name: Deploy to Azure App Service
      #run: |
        #az webapp up --name anc-test-wa-github-01 --resource-group ANC-NP-RG-Webapp-01 --plan anc-test-ASP-github-01 --sku B1 --subscription VCC-WebApp-NP --runtime "DOTNET|8"
