name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@9a10af1be5e3eb7931f48c0290364a131e7ecd70-
      uses: pietrobolcato/install-azure-cli-action@v1.0.1

    - name: Azure Login with User Credentials
      run: |
        az login --use-device-code  # This allows interactive login via a device code

    - name: Deploy to Azure App Service
      run: |
        az webapp up --name anc-test-wa-github-01 --resource-group ANC-NP-RG-Webapp-01 --plan ASP-ANCNPRGWebapp01-81fb --sku B1 --subscription VCC-WebApp-NP --runtime ".NET|8"
